# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ca2f6a52d26a1667c8559fdcb328ddc57ab48fca74e6630e62d34d252e5db40803df633b3f1fa467bb21c6389811bb0558a61588e7221b1946bc62c073d1265

test:
  secret_key_base: eab54db2c0ec534292a9eb3c9ebef8d1f0cb81a2298247ff6ce0758296ca6d7af610360ce36601be3bcdff2dbd07a57bac953e1392bdb425cca9a34d469f8115

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
